name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  pod-lib-lint:
    runs-on: macOS-latest
    strategy:
      matrix:
        podspec: [GoogleSignIn.podspec, GoogleSignInSwiftSupport.podspec]
        flag: [
          "", 
          "--use-libraries", 
          "--use-static-frameworks"
        ]
        include:
          - podspec: GoogleSignInSwiftSupport.podspec
            includePodspecFlag: "--include-podspecs='GoogleSignIn.podspec'"
    steps:
    - uses: actions/checkout@v2
    - name: Update Bundler
      run: bundle update --bundler
    - name: Install Ruby gems with Bundler
      run: bundle install
    - name: Lint podspec using local source
      run: |
        pod lib lint ${{ matrix.podspec }} --verbose \
           ${{ matrix.includePodspecFlag }}  ${{ matrix.flag }}

  spm-build-test:
    runs-on: macOS-latest
    strategy:
      matrix:
        sdk: ['macosx', 'iphonesimulator']
        include:
          - sdk: 'macosx'
            destination: '"platform=OS X,arch=x86_64"'
          - sdk: 'iphonesimulator'
            destination: '"platform=iOS Simulator,name=iPhone 11"'
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.5.1'
    - uses: actions/checkout@v2
    - name: Build unit test target
      run: |
        xcodebuild \
          -scheme GoogleSignIn-Package \
          -sdk ${{ matrix.sdk }} \
          -destination ${{ matrix.destination }} \
          build-for-testing
    - name: Run unit test target
      run: |
        xcodebuild \
          -scheme GoogleSignIn-Package \
          -sdk ${{ matrix.sdk }} \
          -destination ${{ matrix.destination }} \
          test-without-building
